//
//  EventTable.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class EventTable: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _title: String?
    var _address: String?
    var _description: String?
    var _endTime: String?
    var _eventType: String?
    var _expectedAttendence: [String]?
    var _latitude: NSNumber?
    var _longitude: NSNumber?
    var _school: String?
    var _startTime: String?
    var _userEmail: String?
    var _year: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "hotspot-mobilehub-849333022-eventTable"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_title"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_title" : "title",
               "_address" : "address",
               "_description" : "description",
               "_endTime" : "endTime",
               "_eventType" : "eventType",
               "_expectedAttendence" : "expectedAttendence",
               "_latitude" : "latitude",
               "_longitude" : "longitude",
               "_school" : "school",
               "_startTime" : "startTime",
               "_userEmail" : "userEmail",
               "_year" : "year",
        ]
    }
}
